In [5]:
import pandas as pd 
df = pd.read_csv(r'C:\Users\hp\Desktop\preply\lars\project\module 5\preprocessed_data.csv')

In [6]:
df.head()

Name  \
0         EQUITY Factsheet_ A.P. Moller - Maersk A_S   
1              EQUITY Factsheet_ Abbott Laboratories   
2                      EQUITY Factsheet_ AbbVie Inc.   
3                   EQUITY Factsheet_ Adobe Inc. (1)   
4  EQUITY Factsheet_ Advanced Energy Industries Inc.   

                                          Highlights  \
0  ['maersk', 'ebitda', 'billion', 'consensu', 'e...   
1  ['expect', 'total', 'sale', 'contract', 'billi...   
2  ['expect', 'revenu', 'growth', 'billion', 'dec...   
3  ['project', 'sale', 'grow', 'fy', 'fy', 'compa...   
4  ['tight', 'suppli', 'condit', 'hurt', 'aei', '...   

                                Investment Rationale  \
0  ['call', 'sell', 'believ', 'maersk', 'financi'...   
1  ['think', 'share', 'abt', 'outperform', 'marke...   
2  ['opinion', 'share', 'abbvi', 'hold', 'follow'...   
3  ['buy', 'recommend', 'reflect', 'view', 'poten...   
4  ['follow', 'extend', 'period', 'aei', 'abil', ...   

                                    Industry Outlook  
0  ['maintain', 'sector', 'recommend', 'emea', 'i...  
1  ['fundament', 'outlook', 'health', 'care', 'eq...  
2  ['neutral', 'outlook', 'biotech', 'expect', 'l...  
3  ['cfra', 'posit', 'fundament', 'outlook', 'app...  
4  ['neutral', 'fundament', 'outlook', 'electron'...

In [8]:
text = df['Industry Outlook'][0]
text

"['maintain', 'sector', 'recommend', 'emea', 'industri', 'sector', 'neutral', 'believ', 'key', 'issu', 'face', 'sector', 'surg', 'energi', 'price', 'aris', 'concern', 'potenti', 'suppli', 'disrupt', 'middl', 'howev', 'suppli', 'chain', 'disrupt', 'could', 'attribut', 'slower', 'demand', 'good', 'weak', 'economi', 'growth', 'past', 'month', 'shanghai', 'container', 'freight', 'index', 'scfi', 'declin', 'per', 'signal', 'weak', 'demand', 'global', 'movement', 'year', 'date', 'octob', 'emea', 'industri', 'index', 'p', 'versu', 'europ', 'index', 'increas', 'howev', 'emea', 'industri', 'sector', 'perform', 'europ', 'eurozon', 'annual', 'inflat', 'rate', 'drop', 'septemb', 'august', 'expect', 'lower', 'inflat', 'impact', 'posit', 'industri', 'sector', 'earn', 'lower', 'cost', 'widen', 'oper', 'industri', 'player', 'like', 'focu', 'revenu', 'growth', 'via', 'busi', 'volum', 'increas', 'instead', 'averag', 'sell', 'price', 'outlook', 'turn', 'posit', 'inflat', 'moder', 'although', 'partial', '

In [9]:
len(text)

2847

In [2]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

tokenizer = AutoTokenizer.from_pretrained("mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")
model = AutoModelForSequenceClassification.from_pretrained("mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis")

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (5.2.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "


In [3]:
def get_sentiment(tokens):
    outputs = model(**tokens)   # pass tokens to get output
    probabilities = torch.nn.functional.softmax(outputs[0], dim=-1) # Convert retrieved outputs to probabilities
    return probabilities

In [10]:
tokens = tokenizer.encode_plus(text, add_special_tokens=False)
tokens

Token indices sequence length is longer than the specified maximum sequence length for this model (1074 > 512). Running this sequence through the model will result in indexing errors


{'input_ids': [48759, 119, 37205, 3934, 128, 18658, 3934, 128, 43140, 1397, 3934, 128, 991, 13184, 3934, 128, 21267, 1069, 3934, 128, 18658, 3934, 128, 12516, 3934, 128, 8494, 18421, 3934, 128, 5282, 3934, 128, 3006, 257, 3934, 128, 9021, 3934, 128, 18658, 3934, 128, 29, 7150, 3934, 128, 5777, 15696, 3934, 128, 17212, 3934, 128, 17661, 3934, 128, 3865, 38987, 3934, 128, 8024, 1342, 118, 3934, 128, 16714, 3572, 3934, 128, 7779, 14709, 3934, 128, 119, 6502, 462, 3934, 128, 9178, 3623, 3934, 128, 16714, 3572, 3934, 128, 26149, 3934, 128, 7779, 14709, 3934, 128, 17304, 3934, 128, 2611, 24008, 3934, 128, 9996, 8285, 3934, 128, 15509, 3934, 128, 8396, 3934, 128, 25785, 3934, 128, 28310, 118, 3934, 128, 14596, 3934, 128, 33456, 3934, 128, 2151, 3934, 128, 1193, 260, 43673, 3934, 128, 46367, 3934, 128, 18178, 5971, 3934, 128, 18480, 3934, 128, 3866, 9169, 3934, 128, 32639, 179, 3934, 128, 1741, 3934, 128, 13033, 337, 3934, 128, 25785, 3934, 128, 15509, 3934, 128, 9424, 3934, 128, 30191, 1757, 

In [11]:
input_ids = tokens['input_ids']
attention_mask = tokens['attention_mask']

In [12]:
len(tokens['input_ids'])

1074

In [29]:
input_ids[:10]

[48759, 119, 37205, 3934, 128, 18658, 3934, 128, 43140, 1397]

In [32]:
type(input_ids)

list

In [14]:
# Just a demonstration to visualize what the code should do:

start = 0
win_length = 512

total_len = len(input_ids)

loop = True

while loop:
    end = start + win_length
    
    if end >= total_len:
        loop = False
        end = total_len
        
    print(f'start = {start}')
    print(f'end = {end}')
    start = end

start = 0
end = 512
start = 512
end = 1024
start = 1024
end = 1074


In [19]:
total_len = len(input_ids)

In [33]:
def chunk_size(input_ids, attention_mask, total_len):
    prob_list = []
    start = 0
    win_length = 510
    loop = True

    while loop:
        end = start + win_length

        if end >= total_len:
            loop = False 
            end = total_len

        # Defining the text chunk:
        input_ids_chunk = input_ids[start:end]
        attention_mask_chunk = attention_mask[start:end]

        # Referring to specific classes:
        input_ids_chunk = [101] + input_ids_chunk + [102]
        attention_mask_chunk = [1] + attention_mask_chunk + [1]

        # Convert to PyTorch Tensors:
        input_dict = {'input_ids' : torch.Tensor([input_ids_chunk]).long(),
                      'attention_mask' : torch.Tensor([attention_mask_chunk]).int()}
        
        outputs = model(**input_dict)
        probabilities = torch.nn.functional.softmax(outputs[0], dim = -1)
        prob_list.append(probabilities)

        start = end

    return prob_list

In [34]:
prob_list = chunk_size(input_ids, attention_mask, total_len)
prob_list

[tensor([[2.0609e-04, 9.9956e-01, 2.3495e-04]], grad_fn=<SoftmaxBackward0>),
 tensor([[1.1697e-04, 9.9976e-01, 1.2434e-04]], grad_fn=<SoftmaxBackward0>),
 tensor([[9.7182e-05, 9.9982e-01, 8.1408e-05]], grad_fn=<SoftmaxBackward0>)]

In [35]:
stacks = torch.stack(prob_list)
stacks

tensor([[[2.0609e-04, 9.9956e-01, 2.3495e-04]],

        [[1.1697e-04, 9.9976e-01, 1.2434e-04]],

        [[9.7182e-05, 9.9982e-01, 8.1408e-05]]], grad_fn=<StackBackward0>)

In [36]:
shape = stacks.shape
shape

torch.Size([3, 1, 3])

In [37]:
def get_mean_from_prob(prob_list):
    with torch.no_grad():
        stacks = torch.stack(prob_list)

        stacks = stacks.resize(stacks.shape[0], stacks.shape[2])

        mean = stacks.mean(dim=0)

    return mean

In [38]:
mean = get_mean_from_prob(prob_list)
mean

c:\Users\hp\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\_tensor.py:868: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


tensor([1.4008e-04, 9.9971e-01, 1.4690e-04])

In [44]:
torch.argmax(mean).item()

int